name: Lobby
version: '1.0-SNAPSHOT'
main: de.mipa.lobby.Main
api-version: '1.21'
authors: [ mipa ]
permissions:
  lobby.build:
    description: Damit kann man in der Lobby bauen
    default: false
  lobby.sign.create:
    description: Erlaubt das Erstellen von BungeeCord-Schildern
    default: op
  lobby.sign.edit:
    description: Erlaubt das Bearbeiten von Schildern
    default: op